packages:
  - docs
  - playground
  - specs/fixtures/*
  - specs/fixtures/issues/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - oxc-resolver
  - sharp
  - unrs-resolver
  - vue-demi
