blank_issues_enabled: false
contact_links:
  - name: Nuxt Community Discord
    url: https://discord.nuxtjs.org/
    about: Consider asking questions about the module here.
  - name: '@nuxtjs/i18n Documentation'
    url: https://i18n.nuxtjs.org/
    about: Check our documentation before reporting issues or questions.
